version: '3'
services:
  postgres:
    build:
      context: ./postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: openthisworld
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: main
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    environment:
      DATABASE_URL: postgresql://openthisworld:p@ssw0rd@postgres:5432/main

  frontend:
    build:
      context: ./frontend
    ports:
      - '80:80'


volumes:
  postgres-data: